{{/* Copyright 2024 Spark Optima Contributors */}}
{{/* Licensed under the Apache License, Version 2.0 */}}

{{- if .Values.serviceAccount.api.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-optima.api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-optima.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.cli.enabled .Values.serviceAccount.cli.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-optima.cli.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-optima.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/subcomponent: cli
  {{- with .Values.serviceAccount.cli.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
